FORMAT: 1A
HOST: https://tranquil-lake-9594.herokuapp.com/

# Message of the Day API
```A simple``` [MOTD](http://en.wikipedia.org/wiki/motd) API. 

## Root [/]
This resource represents one particular message identified by its *id*.

### Retrieve Message [GET]
Retrieve message
+ Response 200 ()

    + Headers

            content-type: text/html; charset=UTF-8

    + Body
    
            Herokuuu

## Message [/messages/]
This resource represents one particular message identified by its *id*.

### Retrieve Message [GET]
Retrieve a message by its *id*.

+ Response 200 (text/plain)

        Hello Cat!


## Message [/messages/{id}]
This resource represents one particular message identified by its *id*.

+ Parameters
    + id: 1 (string,optional) - ID of the Question in form of an integer
     
### Retrieve Message [GET]
Retrieve a message by its *id*.

+ Response 200 (text/plain)

        Hello World!

### Delete Message [DELETE]
Delete a message.
**Warning:** This action **permanently** removes the message from the database.

+ Response 204